RubyOnRailsApp/config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  root 'static_pages#index'
  resources :clients

  post "/create-client", to: "clients#create", as: "create_client"
  post "/update-client", to: "clients#update", as: "update_client"

  resources :vacations
  post "/create-vacation", to: "vacations#create", as: "create_vacation"
  post "/update-vacation", to: "vacations#update", as: "update_vacation"

  resources :sight_seeings

  post "create_sight_seeing", to: "sight_seeings#create", as "create_sight_seeing"
  post "update_sight_seeing", to: "sight_seeings#update", as "update_sight_seeing"

end

RubyOnRailsApp/app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

RubyOnRailsApp/app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

RubyOnRailsApp/app/models/sight_seeing.rb
class SightSeeing < ActiveRecord::Base
end

RubyOnRailsApp/app/models/vacation.rb
class Vacation < ActiveRecord::Base
  validates :location, presence: true
  validates :price, presence: true
end

RubyOnRailsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

RubyOnRailsApp/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  #CRUD on clients
  # pagini simple care nu fac nimic = GET

  before_action :authenticate_employee!

  def show
    @client = Client.find(params[:id])
  end

  # it's a GET <- afiseaza formularul
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  #it's a POST <- trimite ce a primit de la new la baza de date
  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice]="Client adaugat cu succes."
      redirect_to clients_path
    else
      flash[:error]="Cet cliente n'a pas ete cree."
      redirect_to :back
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(client_params[:id])
    if @client.update(client_params)
      flash[:notice]="Client modificat cu succes."
      redirect_to client_path(@client)
    else
      flash[:error]="Cet cliente n'a pas ete modifier."
      redirect_to :back
    end
  end

  def destroy
    Client.find(params[:id]).destroy
    flash[:notice]="Destroyed!!!"
    redirect_to clients_path
  end


  private
  def client_params
    params.require(:client).permit(:name, :email, :picture, :id)
  end
end

RubyOnRailsApp/app/controllers/sight_seeings_controller.rb
class SightSeeingsController < ApplicationController
end

RubyOnRailsApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

RubyOnRailsApp/app/controllers/vacations_controller.rb
class VacationsController < ApplicationController

    before_action :authenticate_employee!, except: [:index, :show]

  def index
    @vacations = Vacation.all
  end

  def show
    @vacation = Vacation.find(params[:id])
  end


  # apelata ca sa afiseze formularul
  def new
    @vacation = Vacation.new
  end

  def create
    @vacation = Vacation.new(vacation_params)
    if @vacation.save
      flash[:notice]="Successfully added new vacation."
      redirect_to vacations_path
    else
      flash[:error]="Could not create vacation."
      redirect_to :back
    end
  end

  def edit
    @vacation = Vacation.find(params[:id])
  end

  def update
    @vacation = Vacation.find(vacation_params[:id])
    if @vacation.update(vacation_params)
      flash[:notice]="Vacation modified."
      redirect_to vacation_path(@vacation)
    else
      flash[:error]="Vacation was NOT modified."
      redirect_to :back
    end
  end

  def destroy
    Vacation.find(params[:id]).destroy
    flash[:notice]="Destroyed!!!"
    redirect_to vacations_path
  end

  private
  def vacation_params
    params.require(:vacation).permit(:vacation_type, :location, :destination, :start_date, :end_date, :price, :id)
  end
end

RubyOnRailsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRailsApp/app/helpers/clients_helper.rb
module ClientsHelper
end

RubyOnRailsApp/app/helpers/sight_seeings_helper.rb
module SightSeeingsHelper
end

RubyOnRailsApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

RubyOnRailsApp/app/helpers/vacations_helper.rb
module VacationsHelper
end

RubyOnRailsApp/app/views/clients/edit.html.erb
<div class="container">
<h2>Edit client</h2>

<div class="col-xs-5">
<%= form_for(@client, url: update_client_path, method: "POST") do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture, autocomplete: "off", :class=>"form-control" %>
  </div>

  <%= f.hidden_field :id %>

  <div class="actions">
    <%= f.submit "Modify client" %>
  </div>
<% end %>

</div>
</div>

RubyOnRailsApp/app/views/clients/index.html.erb
<div class="container">
  <%= link_to "Create new client", new_client_path, class: "btn btn-default new-client-button"%>
  <% @clients.each do |c|%>
  <div class="client-wrapper">
    <%= c.name%>
    <div class="client-index-options">
    <%= link_to "Show", client_path(c)%>
    <%= link_to "Edit", edit_client_path(c)%>
    <%= link_to 'Destroy', client_path(c), :method => :delete, :data => { :confirm => 'Are you sure?' }%>
  </div>
  </div>
  <% end %>
</div>

RubyOnRailsApp/app/views/clients/new.html.erb
<div class="container">
<h2>Add a new client to our database</h2>

<div class="col-xs-5">
<%= form_for(@client, url: create_client_path, method: "POST") do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture, autocomplete: "off", :class=>"form-control" %>
  </div>


  <div class="actions">
    <%= f.submit "Add new client" %>
  </div>
<% end %>

</div>
</div>

RubyOnRailsApp/app/views/clients/show.html.erb
<div class="container">

  <h3>
    <%= @client.email %>
  </h3>

  <h2>
    <%= @client.name %>
  </h2>


  <div class="field">
    <%= image_tag @client.picture%>
    </a>
  </div>

</div>

RubyOnRailsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketingAgency</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/menu'%>
<%= yield %>


</body>
</html>

RubyOnRailsApp/app/views/shared/_menu.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <nav class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <% if employee_signed_in? %>
          <li>
            <%= link_to root_path do %>
              Welcome
              <%= current_employee.name %>
            <% end %>
          </li>
        <% else employee_signed_in? %>
          <li>
            <%= link_to('Login', new_employee_session_path) %>
          </li>
          <li>
            <%= link_to 'Sign Up',  new_employee_registration_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to('Vacations', vacations_path)%>
        </li>
        <% if employee_signed_in? %>
        <li>
          <%= link_to('Clients', clients_path)%>
        </li>
        <li>
              <%= link_to('Logout', destroy_employee_session_path, :method => :delete) %>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>
<div class="container">
  <div class="col-md-offset-1">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
  </div>
</div>

RubyOnRailsApp/app/views/static_pages/index.html.erb
<h5>Welcome</h5>

RubyOnRailsApp/app/views/vacations/edit.html.erb
<div class="container">
<h2>Add a new vacation to our database</h2>

<div class="col-xs-5">
<%= form_for(@vacation, url: update_vacation_path, method: "POST") do |f| %>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :vacation_type, ["cruise", "tour", "stay"], autofocus: true, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :destination %><br />
    <%= f.select :destination, ["abroad", "country"], autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, autocomplete: "off", :class=>"form-control" %>
  </div>

  <%= f.hidden_field :id %>

  <div class="actions">
    <%= f.submit "Modify vacation" %>
  </div>
<% end %>

</div>
</div>

RubyOnRailsApp/app/views/vacations/index.html.erb
<div class="container">
  <% if employee_signed_in? %>
  <%= link_to "Create new vacation", new_vacation_path, class: "btn btn-default new-client-button"%>
  <% end %>
  <% @vacations.each do |v|%>
  <div class="client-wrapper">
    <h3>
    <%= v.location%>
    </h3>
    <div class="vacation-index-options">
    <%= link_to "Show", vacation_path(v)%>
    <% if employee_signed_in? %>
    <%= link_to "Edit", edit_vacation_path(v)%>
    <%= link_to 'Destroy', vacation_path(v), :method => :delete, :data => { :confirm => 'Are you sure?' }%>
    <% end %>
  </div>
  </div>
  <% end %>
</div>

RubyOnRailsApp/app/views/vacations/new.html.erb
<div class="container">
<h2>Add a new vacation to our database</h2>

<div class="col-xs-5">
<%= form_for(@vacation, url: create_vacation_path, method: "POST") do |f| %>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :vacation_type, ["cruise", "tour", "stay"], autofocus: true, :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :destination %><br />
    <%= f.select :destination, ["abroad", "country"], autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, autocomplete: "off", :class=>"form-control" %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, autocomplete: "off", :class=>"form-control" %>
  </div>


  <div class="actions">
    <%= f.submit "Add new vacation" %>
  </div>
<% end %>

</div>
</div>

RubyOnRailsApp/app/views/vacations/show.html.erb
<div class="container">

  <h2>
    <%= @vacation.location %>
  </h2>

  <h3>
    <%= @vacation.vacation_type %>
  </h3>
  <h3>
    <%= @vacation.destination %>
  </h3>

  <h3>
    <%= @vacation.start_date %>
  </h3>
  <h3>
    <%= @vacation.end_date %>
  </h3>

  <h3>
    <%= @vacation.price %>
  </h3>

</div>